// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/username/shop-api/internal/domain"
)

// ArticleUseCase is an autogenerated mock type for the ArticleUseCase type
type ArticleUseCase struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, req
func (_m *ArticleUseCase) Create(ctx context.Context, req domain.ArticleRequest) (domain.Article, error) {
	ret := _m.Called(ctx, req)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ArticleRequest) (domain.Article, error)); ok {
		return rf(ctx, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ArticleRequest) domain.Article); ok {
		r0 = rf(ctx, req)
	} else {
		r0 = ret.Get(0).(domain.Article)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ArticleRequest) error); ok {
		r1 = rf(ctx, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *ArticleUseCase) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, onlyPublished
func (_m *ArticleUseCase) GetAll(ctx context.Context, onlyPublished bool) ([]domain.Article, error) {
	ret := _m.Called(ctx, onlyPublished)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Article, error)); ok {
		return rf(ctx, onlyPublished)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []domain.Article); ok {
		r0 = rf(ctx, onlyPublished)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Article)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, onlyPublished)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetBySlug provides a mock function with given fields: ctx, slug
func (_m *ArticleUseCase) GetBySlug(ctx context.Context, slug string) (domain.Article, error) {
	ret := _m.Called(ctx, slug)

	if len(ret) == 0 {
		panic("no return value specified for GetBySlug")
	}

	var r0 domain.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Article, error)); ok {
		return rf(ctx, slug)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Article); ok {
		r0 = rf(ctx, slug)
	} else {
		r0 = ret.Get(0).(domain.Article)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, slug)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, req
func (_m *ArticleUseCase) Update(ctx context.Context, id string, req domain.ArticleRequest) (domain.Article, error) {
	ret := _m.Called(ctx, id, req)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Article
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ArticleRequest) (domain.Article, error)); ok {
		return rf(ctx, id, req)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.ArticleRequest) domain.Article); ok {
		r0 = rf(ctx, id, req)
	} else {
		r0 = ret.Get(0).(domain.Article)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.ArticleRequest) error); ok {
		r1 = rf(ctx, id, req)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewArticleUseCase creates a new instance of ArticleUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewArticleUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ArticleUseCase {
	mock := &ArticleUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
