// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/username/shop-api/internal/domain"
)

// MasterProductUseCase is an autogenerated mock type for the MasterProductUseCase type
type MasterProductUseCase struct {
	mock.Mock
}

// GetDetailByID provides a mock function with given fields: ctx, id
func (_m *MasterProductUseCase) GetDetailByID(ctx context.Context, id string) (domain.MasterProductDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetDetailByID")
	}

	var r0 domain.MasterProductDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MasterProductDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MasterProductDetail); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.MasterProductDetail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMasterProductUseCase creates a new instance of MasterProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMasterProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *MasterProductUseCase {
	mock := &MasterProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
