// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	bson "go.mongodb.org/mongo-driver/v2/bson"

	domain "github.com/username/shop-api/internal/domain"

	mock "github.com/stretchr/testify/mock"
)

// MasterProductRepository is an autogenerated mock type for the MasterProductRepository type
type MasterProductRepository struct {
	mock.Mock
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *MasterProductRepository) GetByID(ctx context.Context, id string) (domain.MasterProduct, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.MasterProduct
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.MasterProduct, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.MasterProduct); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.MasterProduct)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetOffersByMasterID provides a mock function with given fields: ctx, masterID
func (_m *MasterProductRepository) GetOffersByMasterID(ctx context.Context, masterID bson.ObjectID) ([]domain.Product, error) {
	ret := _m.Called(ctx, masterID)

	if len(ret) == 0 {
		panic("no return value specified for GetOffersByMasterID")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) ([]domain.Product, error)); ok {
		return rf(ctx, masterID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bson.ObjectID) []domain.Product); ok {
		r0 = rf(ctx, masterID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bson.ObjectID) error); ok {
		r1 = rf(ctx, masterID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMasterProductRepository creates a new instance of MasterProductRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMasterProductRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MasterProductRepository {
	mock := &MasterProductRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
