// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/username/shop-api/internal/domain"
)

// ProductUseCase is an autogenerated mock type for the ProductUseCase type
type ProductUseCase struct {
	mock.Mock
}

// GetDeals provides a mock function with given fields: ctx, limit
func (_m *ProductUseCase) GetDeals(ctx context.Context, limit int64) ([]domain.Product, error) {
	ret := _m.Called(ctx, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetDeals")
	}

	var r0 []domain.Product
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) ([]domain.Product, error)); ok {
		return rf(ctx, limit)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) []domain.Product); ok {
		r0 = rf(ctx, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Product)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, limit)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductByID provides a mock function with given fields: ctx, id
func (_m *ProductUseCase) GetProductByID(ctx context.Context, id string) (domain.ProductDetail, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetProductByID")
	}

	var r0 domain.ProductDetail
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.ProductDetail, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.ProductDetail); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.ProductDetail)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetProductsWithFilter provides a mock function with given fields: ctx, filter
func (_m *ProductUseCase) GetProductsWithFilter(ctx context.Context, filter domain.ProductFilter) (domain.ProductResponse, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetProductsWithFilter")
	}

	var r0 domain.ProductResponse
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProductFilter) (domain.ProductResponse, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.ProductFilter) domain.ProductResponse); ok {
		r0 = rf(ctx, filter)
	} else {
		r0 = ret.Get(0).(domain.ProductResponse)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.ProductFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetStats provides a mock function with given fields: ctx
func (_m *ProductUseCase) GetStats(ctx context.Context) (domain.ProductStats, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetStats")
	}

	var r0 domain.ProductStats
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.ProductStats, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.ProductStats); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.ProductStats)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewProductUseCase creates a new instance of ProductUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewProductUseCase(t interface {
	mock.TestingT
	Cleanup(func())
}) *ProductUseCase {
	mock := &ProductUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
