// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
	domain "github.com/username/shop-api/internal/domain"
)

// PromotionRepository is an autogenerated mock type for the PromotionRepository type
type PromotionRepository struct {
	mock.Mock
}

// Create provides a mock function with given fields: ctx, promo
func (_m *PromotionRepository) Create(ctx context.Context, promo domain.Promotion) (domain.Promotion, error) {
	ret := _m.Called(ctx, promo)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 domain.Promotion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Promotion) (domain.Promotion, error)); ok {
		return rf(ctx, promo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, domain.Promotion) domain.Promotion); ok {
		r0 = rf(ctx, promo)
	} else {
		r0 = ret.Get(0).(domain.Promotion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, domain.Promotion) error); ok {
		r1 = rf(ctx, promo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Delete provides a mock function with given fields: ctx, id
func (_m *PromotionRepository) Delete(ctx context.Context, id string) error {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAll provides a mock function with given fields: ctx, onlyActive
func (_m *PromotionRepository) GetAll(ctx context.Context, onlyActive bool) ([]domain.Promotion, error) {
	ret := _m.Called(ctx, onlyActive)

	if len(ret) == 0 {
		panic("no return value specified for GetAll")
	}

	var r0 []domain.Promotion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, bool) ([]domain.Promotion, error)); ok {
		return rf(ctx, onlyActive)
	}
	if rf, ok := ret.Get(0).(func(context.Context, bool) []domain.Promotion); ok {
		r0 = rf(ctx, onlyActive)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.Promotion)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, bool) error); ok {
		r1 = rf(ctx, onlyActive)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: ctx, id
func (_m *PromotionRepository) GetByID(ctx context.Context, id string) (domain.Promotion, error) {
	ret := _m.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 domain.Promotion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (domain.Promotion, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) domain.Promotion); ok {
		r0 = rf(ctx, id)
	} else {
		r0 = ret.Get(0).(domain.Promotion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: ctx, id, promo
func (_m *PromotionRepository) Update(ctx context.Context, id string, promo domain.Promotion) (domain.Promotion, error) {
	ret := _m.Called(ctx, id, promo)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 domain.Promotion
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Promotion) (domain.Promotion, error)); ok {
		return rf(ctx, id, promo)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, domain.Promotion) domain.Promotion); ok {
		r0 = rf(ctx, id, promo)
	} else {
		r0 = ret.Get(0).(domain.Promotion)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, domain.Promotion) error); ok {
		r1 = rf(ctx, id, promo)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewPromotionRepository creates a new instance of PromotionRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPromotionRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *PromotionRepository {
	mock := &PromotionRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
