version: "2"

run:
  timeout: 5m

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - revive

linters-settings:
  revive:
    confidence: 0.8
    rules:
      - name: package-comments
        disabled: true
      - name: exported
        disabled: true

issues:
  exclude:
    - "at least one file in a package should have a package comment"
    - "should have a package comment"
    - "exported: exported .* should have comment"
    - "comment on exported .* should be of the form"

  exclude-use-default: true
  max-issues-per-linter: 0
  max-same-issues: 0
